version: '3'
services:
  db:
    image: mysql
    restart: always
    container_name: mysql_componse_test
    privileged: true
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=1234@abc
    volumes:
      - /home/xiajun/data/docker_componse_data/mysql/data:/var/lib/mysql
      - /home/xiajun/data/docker_componse_data/mysql/log:/var/log/mysql